### ISSUE TITLE
Support of  `--pre`

### ISSUE THREAD

**Issue by oschrenk** [sportngin/brew-gem#15]
I wanted to install octopress 3.0 rc, which is normally installed via

```
gem install octopress --pre
```

But

```
brew gem install octopress --pre
```

fails with

```
Could not find a valid gem 'octopress'
```

**Comment by NickLaMuro** [comment]
Hi @oschrenk 

Thanks for opening an issue about this.  I have opened [a pull request](https://github.com/sportngin/brew-gem/pull/17) that should solve the issue here, so hopefully we can get that into homebrew core somewhat soon here.

As mentioned in the pull request, it is a bit of a hacky workaround, so I see that proposed method potentially being depreciated in the future, but for now should solve your problem.

**Comment by NickLaMuro** [comment]
@oschrenk I apologize on the time frame that this has taken to get a fix out.  I just had a quick second to look over what needed to be done to finish this off and realized that Octopress now has a official release available, which should allow you to install it with brew-gem.

Again, sorry for the delay on this, and hopefully I can find some time to finish up testing the fix I have in the PR above.

**Comment by anfleene** [comment]
I'm not super comfortable supporting this feature. Closing.
