### ISSUE TITLE
Doesn't install man pages for homebrew

### ISSUE THREAD

**Issue by dabrahams** [sportngin/brew-gem#35]
after `brew gem install kramdown` I have /Users/dave/brew/Cellar/gem-kramdown/1.12.0/gems/kramdown-1.12.0/man/man1/kramdown.1, but `man kramdown` doesn't work.

This fixed it for me.  brew-gem should do something similar automatically.

```
ln -s /Users/dave/brew/Cellar/gem-kramdown/1.12.0/gems/kramdown-1.12.0/man/man1/* ~/brew/share/man/man1
```

Presumably this is broken for info files as well.

**Comment by anfleene** [comment]
I think it's only because kramdown doesn't put the man pages where homebrew [expects them](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#manuals)

> Homebrew expects to find manual pages in #{prefix}/share/man/..., and not in #{prefix}/man/....
> 
> Some software installs to man instead of share/man, so check the output and add a "--mandir=#{man}" to the ./configure line if needed.

I think we would be open to accepting a PR that tried to figure out where `mandir` is and set it accordingly in the generated formula.

**Comment by dabrahams** [comment]
My assumption was that the kramdown gem was putting the manpages in the standard place for gems w.r.t. where brew-gem installs it.  Realistically, I don't think I can do the PR, so feel free to close this if that's the only way it happens.  Just trying to do my bit by reporting problems.
